### ISSUE TITLE
Improve scrollbars on windows

### ISSUE THREAD

**Issue by Rulikkk** [Rulikkk/monthly-report#2]
I would like to see them as good, as on Mac. See screenshot.
<img width="1237" alt="Screenshot 2019-08-09 at 21 03 34" src="https://user-images.githubusercontent.com/2227358/62799393-581db900-bae9-11e9-8d30-916c53f96383.png">

**Comment by Rulikkk** [comment]
Here is how it looks right now.
![image_2019_08_12T13_40_33_405Z](https://user-images.githubusercontent.com/2227358/62869816-31e25e00-bd21-11e9-91cc-6a225dc9e566.png)

**Comment by vadimkorr** [comment]
PR: https://github.com/Rulikkk/monthly-report/pull/4
